/**
 * Generate the GitHub Copilot bundle from export/model.json. Nothing here is authored.
 *
 * The split matters. Copilot loads the instructions file into context for EVERY request in
 * the workspace, so every line in it is paid for on every completion - it holds the rules
 * and the component index and nothing else. The per-component detail lives in one file
 * each, read on demand when the model is actually working on that component.
 *
 * Inverting that - one big file with every class in it - is the common mistake: it makes
 * the always-on cost scale with the size of the library, and the library is going to grow
 * to 39 components.
 *
 *   node tools/build-model.mjs && node tools/build-copilot.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const model = JSON.parse(fs.readFileSync('export/model.json', 'utf8'));
const OUT = 'export/copilot';
const DOCS = path.join(OUT, 'docs');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(DOCS, { recursive: true });

/**
 * Ship the CSS inside the bundle.
 *
 * The first end-to-end run of this export failed on exactly this: the instructions quoted
 * the repo's own paths (src/tokens.css), so a consumer who vendored the bundle got two
 * dead <link> tags and an unstyled page with no error to explain it. A bundle that only
 * works if you also know the producing repo's layout is not a bundle. The two files are
 * copied in and referenced relatively, so the directory is self-contained and portable.
 */
const CSS = path.join(OUT, 'css');
fs.mkdirSync(CSS, { recursive: true });
for (const f of model.stylesheets) fs.copyFileSync(f, path.join(CSS, path.basename(f)));

/* ---- always-on instructions --------------------------------------------- */
const built = model.components.length;
const total = model.coverage.sets;

const index = model.components
  .map((c) => `| \`${c.baseClass}\` | ${c.name} | ${c.classes.length} | \`docs/${c.doc}\` |`)
  .join('\n');

const instructions = `---
applyTo: "**"
---

# ${model.name}

A framework-neutral CSS library. Classes and custom properties, no framework, no build step.

## Load it once

The stylesheets ship inside this bundle, in \`css/\`. Copy the whole directory into the
project and link them from wherever it landed - \`tokens.css\` **first**, because
\`styles.css\` depends on its custom properties:

\`\`\`html
<link rel="stylesheet" href="css/tokens.css" />
<link rel="stylesheet" href="css/styles.css" />
\`\`\`

Dark mode is an attribute and it works on **any** element, so a dark region can be scoped
inside a light page:

\`\`\`html
<html data-${model.prefix}-theme="dark">
\`\`\`

${model.counts.themed} of ${model.counts.tokens} tokens have a dark counterpart. Components
never branch on theme themselves - switching the attribute is the whole mechanism.

## Rules

${model.rules.map((r) => `- ${r}`).join('\n')}

## Components

${built} of ${total} component sets are built. **If a component is not in this table it does
not exist yet - say so rather than inventing a class name for it.**

| Base class | Component | Classes | Detail |
|---|---|---|---|
${index}

Read the detail file before using a component. It carries the variants, the exact values,
and the Figma node every value was measured on.

## Tokens

Two tiers. Primitives hold raw values; semantic tokens name a role and point at a
primitive. **Use semantic tokens only.**

\`\`\`css
--${model.prefix}-foreground-primary: var(--${model.prefix}-neutral-700);
\`\`\`

Never hard-code a colour, spacing, radius or font size. If no token fits, say so - do not
approximate one.

## What this library does not have

- **No icons.** The glyphs are Font Awesome and are not bundled; licensing is unresolved.
  Supply your own \`<svg>\`; components size it and set \`fill: currentColor\`.
- **No webfont.** Outfit is referenced with a system fallback but is not bundled or
  licensed, so text renders in the fallback unless the app loads Outfit itself.
- **No charts.** The palette is a single white swatch in both themes, so no charting
  component can be built against it.
`;

fs.writeFileSync(path.join(OUT, 'v27.instructions.md'), instructions, 'utf8');

/* ---- per-component detail ------------------------------------------------ */
for (const c of model.components) {
  const body = fs.readFileSync(path.join('docs', c.doc), 'utf8');
  const classes = c.classes.map((x) => `\`.${x}\``).join(', ');
  const header = `<!-- Generated by tools/build-copilot.mjs from docs/${c.doc}. Do not edit here. -->\n\n`;
  const footer = `\n## All classes in this component\n\n${classes}\n`;
  fs.writeFileSync(path.join(DOCS, c.doc), header + body.trimEnd() + '\n' + footer, 'utf8');
}

/* ---- token reference, read on demand ------------------------------------- */
const byTier = {};
for (const t of model.tokens) (byTier[t.tier] ??= []).push(t);
let tokenMd = `<!-- Generated by tools/build-copilot.mjs. Do not edit here. -->\n\n# Tokens\n\n`;
for (const tier of ['semantic', 'typography', 'dimension', 'primitive']) {
  const rows = byTier[tier] ?? [];
  if (!rows.length) continue;
  tokenMd += `## ${tier} (${rows.length})\n\n| Token | Light | Dark |\n|---|---|---|\n`;
  for (const t of rows) tokenMd += `| \`${t.name}\` | \`${t.value ?? ''}\` | ${t.dark ? `\`${t.dark}\`` : '-'} |\n`;
  tokenMd += '\n';
}
fs.writeFileSync(path.join(DOCS, 'TOKENS.md'), tokenMd, 'utf8');

const files = fs.readdirSync(DOCS);
const kb = (p) => (fs.statSync(p).size / 1024).toFixed(1);
console.log(`-> ${OUT}/v27.instructions.md  (${kb(path.join(OUT, 'v27.instructions.md'))} KB, always in context)`);
console.log(`-> ${DOCS}/  ${files.length} files, read on demand`);
console.log(`   always-on cost is ${kb(path.join(OUT, 'v27.instructions.md'))} KB and does not grow with the detail files`);
