/**
 * Turn the Figma variables export into src/tokens.css.
 *
 *   node tools/build-tokens.mjs
 *
 * This is a script rather than a transcription because the design system will change and
 * the token layer has to be reproducible. Nothing in tokens.css is written by hand.
 *
 * Two tiers are preserved deliberately. Figma's Semantic collection aliases the Primitives
 * collection - Foreground/Primary is {Neutral.700}, not #3e3e3e - and that indirection is
 * what makes theming and rebranding possible. Resolving aliases to hex would flatten the
 * system into a list of colours and throw the structure away, so an alias becomes
 * var(--v27-neutral-700) and the relationship stays visible in the output.
 *
 * Source: tokens/variables.json, exported from the V27 Design System Figma file.
 */
import fs from 'node:fs';
import path from 'node:path';

const PREFIX = 'v27';
const SRC = 'tokens/variables.json';
const OUT = 'src/tokens.css';
/**
 * Any element, not :root. `:root[data-v27-theme="dark"]` only ever matches <html>, so
 * scoping a dark region inside a light page silently does nothing - the attribute applies
 * and no value changes. Custom properties inherit, so redeclaring them on any element
 * themes that element's whole subtree. Specificity is unchanged against :root (0,1,0 both
 * ways) and this block comes later, so it still wins at the document level.
 */
const DARK_SELECTOR = `[data-${PREFIX}-theme="dark"]`;

const raw = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const collections = Object.fromEntries(raw.map((c) => [Object.keys(c)[0], Object.values(c)[0]]));

const slug = (s) =>
  String(s)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

/**
 * Group names shortened for use in CSS. This is the only place a Figma name is changed,
 * it changes no value, and it is recorded in FINDINGS.md. Figma's group is "Spacing and
 * Padding", which slugs to --v27-spacing-and-padding-xxs and appears in nearly every rule
 * in the library.
 */
const GROUP_ALIAS = { 'spacing-and-padding': 'spacing' };

/**
 * A custom property name from a token's path. The group is dropped when the token already
 * repeats it - Border/"Border inverted" should be --v27-border-inverted, not
 * --v27-border-border-inverted.
 */
function nameOf(pathParts) {
  const parts = pathParts.map(slug);
  parts[0] = GROUP_ALIAS[parts[0]] ?? parts[0];
  if (parts.length > 1 && parts[1].startsWith(parts[0] + '-')) parts.splice(0, 1);
  return `--${PREFIX}-${parts.join('-')}`;
}

/** Walk a mode tree, yielding [pathParts, tokenObject]. */
function* walk(node, trail = []) {
  for (const [key, value] of Object.entries(node)) {
    if (value && typeof value === 'object' && '$value' in value) yield [[...trail, key], value];
    else if (value && typeof value === 'object') yield* walk(value, [...trail, key]);
  }
}

/** {Neutral.700} -> var(--v27-neutral-700). Anything else is a literal. */
function valueOf(token) {
  const v = token.$value;
  if (typeof v === 'number') return `${v}px`;
  const alias = String(v).match(/^\{([^}]+)\}$/);
  if (!alias) return String(v);
  return `var(--${PREFIX}-${alias[1].split('.').map(slug).join('-')})`;
}

/** Emit one block of declarations, grouped and commented by their top-level group. */
function block(tokens) {
  const byGroup = new Map();
  for (const [parts, token] of tokens) {
    const group = parts[0];
    if (!byGroup.has(group)) byGroup.set(group, []);
    byGroup.get(group).push([nameOf(parts), valueOf(token)]);
  }
  const out = [];
  for (const [group, rows] of byGroup) {
    out.push(`  /* ${group} */`);
    const width = Math.max(...rows.map(([n]) => n.length));
    for (const [n, v] of rows) out.push(`  ${n.padEnd(width)}: ${v};`);
    out.push('');
  }
  if (out.at(-1) === '') out.pop();
  return out.join('\n');
}

const dimensions = [...walk(collections.Dimensions.modes['Mode 1'])];
const primitives = [...walk(collections.Primitives.modes['Mode 1'])];
const light = [...walk(collections.Semantic.modes.Lightmode)];
const dark = [...walk(collections.Semantic.modes.Darkmode)];

// The two semantic modes must stay symmetric; a name in one and not the other means a
// theme that silently falls back to the light value.
const names = (t) => new Set(t.map(([p]) => nameOf(p)));
const lightOnly = [...names(light)].filter((n) => !names(dark).has(n));
const darkOnly = [...names(dark)].filter((n) => !names(light).has(n));

const css = `/* V27 Design System - design tokens.
 *
 * GENERATED by tools/build-tokens.mjs from tokens/variables.json. Do not edit by hand:
 * the next export overwrites it, and a hand-edit silently desynchronises the library
 * from Figma.
 *
 * Two tiers. Primitives hold the raw values; semantic tokens name a role and point at a
 * primitive. Component CSS must only ever reference the semantic tier.
 *
 * Dark mode is an attribute, matching Figma's Lightmode / Darkmode modes:
 *     <html data-${PREFIX}-theme="dark">
 * It works on any element, not just the root, so a dark region can be scoped inside a
 * light page. It is not wired to prefers-color-scheme, because Figma defines the two modes
 * explicitly rather than deferring to the operating system.
 *
 * ${primitives.length} primitives - ${dimensions.length} dimensions - ${light.length} semantic (x2 modes)
 */

:root {
${block(dimensions)}

${block(primitives)}

  /* ---- Semantic: Lightmode ---- */
${block(light)}
}

${DARK_SELECTOR} {
  /* ---- Semantic: Darkmode ----
   * Foreground/Theme, Background/Theme and Border/Theme deliberately change hue here,
   * from pink to blue. That is what Figma specifies; see FINDINGS.md. */
${block(dark)}
}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, css, 'utf8');

const nonAscii = (css.match(/[^\x00-\x7F]/g) || []).length;
console.log(`-> ${OUT}`);
console.log(`   ${dimensions.length} dimensions, ${primitives.length} primitives, ${light.length} semantic x 2 modes`);
console.log(`   ${(css.length / 1024).toFixed(1)} KB, ${css.split('\n').length} lines`);

const problems = [];
if (nonAscii) problems.push(`${nonAscii} non-ASCII characters`);
if (lightOnly.length) problems.push(`light-only tokens: ${lightOnly.join(', ')}`);
if (darkOnly.length) problems.push(`dark-only tokens: ${darkOnly.join(', ')}`);

// Every var() must resolve to something declared in this file.
const declared = new Set([...css.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gm)].map((m) => m[1]));
const referenced = new Set([...css.matchAll(/var\((--[a-z0-9-]+)\)/g)].map((m) => m[1]));
const dangling = [...referenced].filter((r) => !declared.has(r));
if (dangling.length) problems.push(`unresolved references: ${dangling.join(', ')}`);

if (problems.length) {
  console.error('\nFAIL');
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log(`   ${declared.size} custom properties, every reference resolves`);
